"""The review protocol's invariants, enforced by the test suite (`c-0001.6`).

`dashboard/review.py check` is the reference implementation and it is owned by
Cowork. This runs it, so a broken cycle file or a torn inbox fails here rather
than being discovered when someone reads the board and believes it.

It also pins the two things on *this* side of the lane that the protocol depends
on: that `data/review/` is versioned while its derived state is not, and that
`daily.py` actually calls the emitter. The board is only as good as the
reporting, and reporting that is not wired is reporting that will not happen.
"""
from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
REVIEW_PY = REPO / "dashboard" / "review.py"

#: Python on Windows defaults stdout to cp1252 and `review.py` prints the
#: charter, whose critical path contains a U+2192 arrow. Without this the
#: subprocess dies with UnicodeEncodeError and the test would report a protocol
#: violation that does not exist. Raised with Cowork as a finding.
ENV = {**os.environ, "PYTHONIOENCODING": "utf-8"}


def _run(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run([sys.executable, str(REVIEW_PY), *args],
                          cwd=REPO, capture_output=True, text=True,
                          timeout=120, env=ENV)


def _git(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(["git", *args], cwd=REPO, capture_output=True, text=True)


def test_review_py_exists():
    """It is tracked now, so its absence is a defect rather than an environment."""
    assert REVIEW_PY.exists(), (
        f"{REVIEW_PY} is missing. It is tracked in git and the session loop, the "
        f"post-commit hook and this suite all call it.")


def test_review_protocol_invariants_hold():
    """Cycles immutable, ids stable, status derived, every work_order checkable."""
    proc = _run("check")
    assert proc.returncode == 0, (
        "review.py check failed -- the board cannot be trusted until it passes:\n"
        f"{proc.stdout}\n{proc.stderr}")


def test_review_check_survives_a_cp1252_stdout():
    """The console is Windows-only and non-ASCII reaches stdout via the charter.

    Pinned because `review.py emit` is wired into the harvest and the post-commit
    hook: if a non-ASCII cycle file can kill it, a scheduled run stops reporting
    and the board silently goes stale.
    """
    proc = subprocess.run([sys.executable, str(REVIEW_PY), "check"],
                          cwd=REPO, capture_output=True, text=True, timeout=120,
                          env={**os.environ, "PYTHONIOENCODING": "cp1252"})
    assert "UnicodeEncodeError" not in (proc.stderr or ""), (
        "review.py check dies on a cp1252 stdout. Non-ASCII in charter.json or a "
        "cycle file then breaks the harvest's reporting step. Fix belongs in "
        "review.py (reconfigure stdout to utf-8); daily.py and the hook force "
        "PYTHONIOENCODING as a guard.")


# ------------------------- the wiring, on our side -------------------------

def test_daily_py_calls_both_emitters():
    """A board nobody emits to is a board that reads as of the last manual run."""
    src = (REPO / "scripts" / "daily.py").read_text(encoding="utf-8")
    assert "emit_build_status.py" in src, "daily.py does not emit the build monitor"
    assert "review.py" in src, "daily.py does not emit the review board"
    assert "PYTHONIOENCODING" in src, (
        "daily.py must force PYTHONIOENCODING for the emitters; without it a "
        "non-ASCII cycle file kills the reporting step under Windows' cp1252")


@pytest.mark.parametrize("path", [
    "data/review/charter.json",
    "data/review/inbox.jsonl",
    "data/review/heartbeat.jsonl",
    "data/review/cycles/c-0001.json",
])
def test_review_record_is_versioned(path):
    """The charter, the sealed cycles and the inbox are how this build was
    steered. They are source, not derived output."""
    assert _git("check-ignore", "-q", path).returncode != 0, (
        f"{path} is gitignored. data/ is ignored wholesale, so data/review/ needs "
        f"an explicit re-inclusion in .gitignore or the record of every decision "
        f"lives on one machine.")


@pytest.mark.parametrize("path", [
    "data/results/review_state.json",
    "data/results/review_state.js",
])
def test_derived_review_state_is_not_versioned(path):
    """Tracking a derived file produces a merge conflict on every run."""
    assert _git("check-ignore", "-q", path).returncode == 0, (
        f"{path} is tracked. It is regenerated by `review.py emit` on every "
        f"harvest and every commit.")
